### ISSUE TITLE
Help for how to run exe files ?

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [Weilbyte/box#1]
Hey there great work
But how to run and open application with this image on armv64?
Running command you mentioned giving this error

sudo docker run -it --rm -e BOX64_LOG=0 -v $(pwd):/binary weilbyte/box:debian-11 /binary/hello
Box64 with Dynarec v0.1.9 008f591 built on May  1 2022 02:49:57
Error: file is not found (check BOX64_PATH)

**Comment by Weilbyte** [comment]
Hi, just to confirm, is the application in your current working directory when you run that command on the host?

**Comment by Morakhiyasaiyam** [comment]
> Hi, just to confirm, is the application in your current working directory when you run that command on the host?

Ok so it is mounting current working directory to container and then running it ..
And please add in guide that hello binary is not in container images to prevent confusion
And also if i want container to keep running how to do that ?

And also feature request for gui !👍

**Comment by Weilbyte** [comment]
Hi, I have changed it up to specify that the binary is being mounted. GUI is not possible. And to keep it running you replace `-it --rm` with `-d` (runs container detached).

**Comment by Morakhiyasaiyam** [comment]
> Hi, I have changed it up to specify that the binary is being mounted. GUI is not possible. And to keep it running you replace `-it --rm` with `-d` (runs container detached).

Yes thank for your work.
But box86 and box64 is capable of running gui app and i we can install gui env in image then why not implement ?

**Comment by Weilbyte** [comment]
@Morakhiyasaiyam I will have to see more about it in the future. If you are running an X server, try adding `-e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/` to the command (after the existing `-e` arg).
