### ISSUE TITLE
Box86 works on arm linux, not on arm macos

### ISSUE THREAD

**Issue by jacobmichels** [Weilbyte/box#2]
Hey, thanks for building this. It works great on my arm64 linux host machine, but box86 doesn't work on my arm64 mac host.

When I run the box86 command in the arm64v8 container running on my mac host, I get `bash: /usr/local/bin/box86: cannot execute binary file: Exec format error`. The same image running on an arm64 ubuntu cloud vm is able to start and run box86 just fine. I'm not a docker expert, but I would've expected the containers to behave identically no matter the host OS. I built the image on the linux VM, then imported it onto my mac.

Do you have any guesses as to what's going wrong here? I don't need a real solution, I'm just wanna know what the problem is.

**Comment by Weilbyte** [comment]
As far as I can see, Apple M1/M2 processors do not appear to have 32-bit support.

**Comment by jacobmichels** [comment]
Yeah that makes sense. Thanks!
